---
- hosts: ec2-13-54-211-146.ap-southeast-2.compute.amazonaws.com
  user: ubuntu
  become: true
  roles:
    - role: nginxinc.nginx-oss

  tasks:
    - name: Copy the nginx configuration file
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - restart nginx

  handlers:
    - name: restart nginx
      action: service name=nginx state=restarted
